FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /src
EXPOSE 80
COPY ./*.sln ./
COPY ./Flixtube.AzureStorage/*.csproj ./Flixtube.AzureStorage/
RUN ["dotnet","restore"]
CMD ["dotnet","watch","run","--no-launch-profile","--project","Flixtube.AzureStorage"]