#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers: 
      - name: history
        image: $AZURE_CONTAINER_REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_VERSION
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: FLIXTUBE_HISTORY_PORT
          value: "4020"
        - name: FLIXTUBE_HISTORY_CONNECTION_STRING
          value: Data Source=db,1433;Initial Catalog=history;User Id=sa;Password=P@55w0rd;Encrypt=Yes;TrustServerCertificate=Yes;MultipleActiveResultSets=True;
        - name: FLIXTUBE_HISTORY_SEED_DATABASE
          value: "False"
        - name: FLIXTUBE_RABBIT_MQ_HOST
          value: amqp://rabbit_user:rabbit_password@rabbit:5672
        ports:
        - containerPort: 4020
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4020
      targetPort: 4020
