FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
EXPOSE 80
COPY ./Flixtube.VideoStreaming/*.csproj ./
RUN dotnet restore
COPY ./Flixtube.VideoStreaming .
# RUN dotnet build -c Release -o /app/build
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
CMD dotnet Flixtube.VideoStreaming.dll